export {default as UserAdd} from './components/UserAdd'
export {default as UserDetail} from 'features/user/components/UserDetail'
export {default as UserList} from 'features/user/components/UserList'
export {default as UserLogin} from 'features/user/components/UserLogin'
export {default as UserModify} from 'features/user/components/UserModify'
export {default as UserRemove} from 'features/user/components/UserRemove'